import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { CarrinhoProvider } from "@/features/carrinho/context/carrinho.context";
import { HistoricoProvider} from "@/features/historico/context/extrato.context"
import "../styles/globals.css";

import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import { MuiProvider } from "./providers/MuiProvider";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MuiProvider>
          <HistoricoProvider>
            <CarrinhoProvider>
              <div className="container-content-pages">
                <Header />
               
                <main style={{ flexGrow: 1 }}>{children}</main>
                <Footer />
              </div>
            </CarrinhoProvider>
          </HistoricoProvider>
        </MuiProvider>
      </body>
    </html>
  );
}
